#!/usr/bin/env bash
set -Eeuo pipefail

# One workspace owns one learner mode at a time.  Development and packaged
# Fluent Lab both write the same profile, so allowing them to overlap creates
# a race that port checks alone cannot explain.  The lock is deliberately a
# tiny, workspace-owned directory; it never touches Docker resources or user
# data.

ROOT="${ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)}"
MODE_LOCK_DIR="${MODE_LOCK_DIR:-$ROOT/.workspace/mode-lock}"
MODE_LOCK_STATE="$MODE_LOCK_DIR/state.json"
source "$ROOT/scripts/workspace-contract.sh" --
command -v jq >/dev/null 2>&1 || { echo 'Missing command: jq' >&2; exit 1; }
command -v curl >/dev/null 2>&1 || { echo 'Missing command: curl' >&2; exit 1; }

usage() {
  cat <<'USAGE'
Usage: scripts/mode-guard.sh <acquire|release|check> [development|production]

The guard is workspace-local and fail-closed.  A stale lock is removed only
when its recorded owner is gone and both learner endpoints are offline.
USAGE
}

mode_url() {
  case "$1" in
    development) printf '%s' "${MODE_GUARD_DEV_URL:-$WS_LAB_DEV_URL}" ;;
    production) printf '%s' "${MODE_GUARD_PACKAGE_URL:-$WS_LAB_PACKAGE_URL}" ;;
    *) echo "Unknown mode: $1" >&2; exit 2 ;;
  esac
}

pid_alive() {
  local pid="$1"
  [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null
}

endpoint_online() {
  local url="$1"
  curl --silent --show-error --fail --max-time 1 "$url" >/dev/null 2>&1
}

any_learner_endpoint_online() {
  endpoint_online "$(mode_url development)" || endpoint_online "$(mode_url production)"
}

read_state() {
  [[ -s "$MODE_LOCK_STATE" ]] || return 1
  jq -e '(.schemaVersion == "workspace-mode-lock.v1") and (.mode == "development" or .mode == "production") and (.pid | numbers)' "$MODE_LOCK_STATE" >/dev/null 2>&1
}

print_conflict() {
  local mode="$1"
  local pid="$2"
  echo "Workspace mode conflict: ${mode} owns the learner profile (pid=${pid})." >&2
  echo "Stop the existing mode with 'pnpm down' before starting another mode." >&2
}

acquire() {
  local requested="$1"
  local owner_pid="${MODE_LOCK_PID:-$PPID}"
  mode_url "$requested" >/dev/null
  [[ "$owner_pid" =~ ^[0-9]+$ ]] || { echo "Invalid MODE_LOCK_PID: $owner_pid" >&2; exit 2; }
  mkdir -p "$(dirname -- "$MODE_LOCK_DIR")"

  if [[ ! -e "$MODE_LOCK_DIR" ]] && any_learner_endpoint_online; then
    echo 'A learner endpoint is already online without a workspace mode lock.' >&2
    echo 'Stop the unmanaged learner process, then retry; no resources were changed.' >&2
    exit 1
  fi

  # mkdir is the atomic claim.  Never overwrite a lock that another launcher
  # may have just created.
  if mkdir "$MODE_LOCK_DIR" 2>/dev/null; then
    if ! jq -n \
      --arg mode "$requested" \
      --argjson pid "$owner_pid" \
      --arg createdAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
      '{schemaVersion:"workspace-mode-lock.v1",mode:$mode,pid:$pid,createdAt:$createdAt}' \
      >"$MODE_LOCK_STATE"; then
      rmdir "$MODE_LOCK_DIR" 2>/dev/null || true
      echo 'Could not write workspace mode lock.' >&2
      exit 1
    fi
    printf 'Workspace mode lock acquired: %s (pid=%s)\n' "$requested" "$owner_pid"
    exit 0
  fi

  # A malformed lock is not safe to guess about.  If a previous owner is
  # provably gone and both learner endpoints are offline, it is a recoverable
  # stale lock generated by this script and may be reaped.
  if ! read_state; then
    echo "Workspace mode lock is malformed: $MODE_LOCK_STATE" >&2
    echo 'Inspect it manually; no lock or process was removed.' >&2
    exit 1
  fi
  local current_mode current_pid
  current_mode="$(jq -r '.mode' "$MODE_LOCK_STATE")"
  current_pid="$(jq -r '.pid' "$MODE_LOCK_STATE")"
  if pid_alive "$current_pid" || any_learner_endpoint_online; then
    print_conflict "$current_mode" "$current_pid"
    exit 1
  fi
  rm -f "$MODE_LOCK_STATE"
  if ! rmdir "$MODE_LOCK_DIR" 2>/dev/null; then
    echo 'Stale mode lock could not be removed safely; retry after inspection.' >&2
    exit 1
  fi
  exec "$0" acquire "$requested"
}

release() {
  if [[ ! -e "$MODE_LOCK_DIR" ]]; then
    printf 'Workspace mode lock already clear.\n'
    exit 0
  fi
  if ! read_state; then
    echo "Workspace mode lock is malformed: $MODE_LOCK_STATE" >&2
    echo 'Refusing to remove an unknown lock.' >&2
    exit 1
  fi
  local current_mode current_pid
  current_mode="$(jq -r '.mode' "$MODE_LOCK_STATE")"
  current_pid="$(jq -r '.pid' "$MODE_LOCK_STATE")"
  if pid_alive "$current_pid" || endpoint_online "$(mode_url "$current_mode")"; then
    echo "Cannot release live ${current_mode} mode (pid=${current_pid})." >&2
    echo 'Stop the owning launcher and its learner endpoint first.' >&2
    exit 1
  fi
  rm -f "$MODE_LOCK_STATE"
  rmdir "$MODE_LOCK_DIR"
  printf 'Workspace mode lock released: %s\n' "$current_mode"
}

check() {
  if [[ ! -e "$MODE_LOCK_DIR" ]]; then
    if any_learner_endpoint_online; then
      echo 'Workspace mode conflict: learner endpoint is online without a mode lock.' >&2
      echo 'Stop the unmanaged launcher before starting or trusting a workspace mode.' >&2
      exit 1
    fi
    printf '%s\n' '{"schemaVersion":"workspace-mode-lock.v1","state":"clear"}'
    exit 0
  fi
  if ! read_state; then
    echo "Workspace mode lock is malformed: $MODE_LOCK_STATE" >&2
    exit 1
  fi
  local current_mode current_pid live='false' endpoint='offline'
  current_mode="$(jq -r '.mode' "$MODE_LOCK_STATE")"
  current_pid="$(jq -r '.pid' "$MODE_LOCK_STATE")"
  if pid_alive "$current_pid"; then live='true'; fi
  if endpoint_online "$(mode_url "$current_mode")"; then endpoint='online'; fi
  jq -n --arg mode "$current_mode" --argjson pid "$current_pid" --arg live "$live" --arg endpoint "$endpoint" \
    '{schemaVersion:"workspace-mode-lock.v1",state:"held",mode:$mode,pid:$pid,ownerLive:($live == "true"),endpoint:$endpoint}'
}

action="${1:-}"
case "$action" in
  acquire)
    [[ $# -eq 2 ]] || { usage >&2; exit 2; }
    acquire "$2"
    ;;
  release)
    [[ $# -eq 1 ]] || { usage >&2; exit 2; }
    release
    ;;
  check)
    [[ $# -eq 1 ]] || { usage >&2; exit 2; }
    check
    ;;
  *) usage >&2; exit 2 ;;
esac
